- name: Gurke
  durability: 21
- name: Aprikose
  durability: 4
- name: Cherrytomaten
  durability: 10
- name: Süßkartoffel
  durability: 30
- name: Eis
  durability: 40
- name: Karotte
  durability: 20
- name: Apfel
  durability: 14
- name: Erdbeere
  durability: 7
- name: KiBa
  durability: 5
- name: Milch
  durability: 3
- name: Cheddar
  durability: 25
- name: Schokolade
  durability: 180